INSERT INTO user_sector(id, name, is_agreement_accepted) VALUES ('888','Test name ONE', '1');

INSERT INTO user_to_sector(id, user_id, sector_id) VALUES ('777', '888', '324');
INSERT INTO user_to_sector(id, user_id, sector_id) VALUES ('999', '888', '19');

INSERT INTO sector(id, value) VALUES ('1','Manufacturing');
INSERT INTO sector(id, value) VALUES ('19','Construction materials');
INSERT INTO sector(id, value) VALUES ('18','Electronics and Optics');
INSERT INTO sector(id, value) VALUES ('6','Food and Beverage');
INSERT INTO sector(id, value) VALUES ('324','Bakery & confectionery products');
INSERT INTO sector(id, value) VALUES ('43','Beverages');
INSERT INTO sector(id, value) VALUES ('42','Fish & fish products');
INSERT INTO sector(id, value) VALUES ('40','Meat & meat products');
INSERT INTO sector(id, value) VALUES ('39','Milk & dairy products');
INSERT INTO sector(id, value) VALUES ('437','Other');
INSERT INTO sector(id, value) VALUES ('378','Sweets & snack food');
INSERT INTO sector(id, value) VALUES ('13','Furniture');
INSERT INTO sector(id, value) VALUES ('389','Bathroom/sauna');
INSERT INTO sector(id, value) VALUES ('385','Bedroom');
INSERT INTO sector(id, value) VALUES ('390','Children''s room');
INSERT INTO sector(id, value) VALUES ('98','Kitchen');
INSERT INTO sector(id, value) VALUES ('101','Living room');
INSERT INTO sector(id, value) VALUES ('392','Office');
INSERT INTO sector(id, value) VALUES ('394','Other (Furniture)');
INSERT INTO sector(id, value) VALUES ('341','Outdoor');
INSERT INTO sector(id, value) VALUES ('99','Project furniture');
INSERT INTO sector(id, value) VALUES ('12','Machinery');
INSERT INTO sector(id, value) VALUES ('94','Machinery components');
INSERT INTO sector(id, value) VALUES ('91','Machinery equipment/tools');
INSERT INTO sector(id, value) VALUES ('224','Manufacture of machinery');
INSERT INTO sector(id, value) VALUES ('97','Maritime');
INSERT INTO sector(id, value) VALUES ('271','Aluminium and steel workboats');
INSERT INTO sector(id, value) VALUES ('269','Boat/Yacht building');
INSERT INTO sector(id, value) VALUES ('230','Ship repair and conversion');
INSERT INTO sector(id, value) VALUES ('93','Metal structures');
INSERT INTO sector(id, value) VALUES ('508','Other');
INSERT INTO sector(id, value) VALUES ('227','Repair and maintenance service');
INSERT INTO sector(id, value) VALUES ('11','Metalworking');
INSERT INTO sector(id, value) VALUES ('67','Construction of metal structures');
INSERT INTO sector(id, value) VALUES ('263','Houses and buildings');
INSERT INTO sector(id, value) VALUES ('267','Metal products');
INSERT INTO sector(id, value) VALUES ('542','Metal works');
INSERT INTO sector(id, value) VALUES ('75','CNC-machining');
INSERT INTO sector(id, value) VALUES ('62','Forgings, Fasteners');
INSERT INTO sector(id, value) VALUES ('69','Gas, Plasma, Laser cutting');
INSERT INTO sector(id, value) VALUES ('66','MIG, TIG, Aluminum welding');
INSERT INTO sector(id, value) VALUES ('9','Plastic and Rubber');
INSERT INTO sector(id, value) VALUES ('54','Packaging');
INSERT INTO sector(id, value) VALUES ('556','Plastic goods');
INSERT INTO sector(id, value) VALUES ('559','Plastic processing technology');
INSERT INTO sector(id, value) VALUES ('55','Blowing');
INSERT INTO sector(id, value) VALUES ('57','Moulding');
INSERT INTO sector(id, value) VALUES ('53','Plastics welding and processing');
INSERT INTO sector(id, value) VALUES ('560','Plastic profiles');
INSERT INTO sector(id, value) VALUES ('5','Printing');
INSERT INTO sector(id, value) VALUES ('148','Advertising');
INSERT INTO sector(id, value) VALUES ('150','Book/Periodicals printing');
INSERT INTO sector(id, value) VALUES ('145','Labelling and packaging printing');
INSERT INTO sector(id, value) VALUES ('7','Textile and Clothing');
INSERT INTO sector(id, value) VALUES ('44','Clothing');
INSERT INTO sector(id, value) VALUES ('45','Textile');
INSERT INTO sector(id, value) VALUES ('8','Wood');
INSERT INTO sector(id, value) VALUES ('337','Other (Wood)');
INSERT INTO sector(id, value) VALUES ('51','Wooden building materials');
INSERT INTO sector(id, value) VALUES ('47','Wooden houses');
INSERT INTO sector(id, value) VALUES ('3','Other');
INSERT INTO sector(id, value) VALUES ('37','Creative industries');
INSERT INTO sector(id, value) VALUES ('29','Energy technology');
INSERT INTO sector(id, value) VALUES ('33','Environment');
INSERT INTO sector(id, value) VALUES ('2','Service');
INSERT INTO sector(id, value) VALUES ('25','Business services');
INSERT INTO sector(id, value) VALUES ('35','Engineering');
INSERT INTO sector(id, value) VALUES ('28','Information Technology and Telecommunications');
INSERT INTO sector(id, value) VALUES ('581','Data processing, Web portals, E-marketing');
INSERT INTO sector(id, value) VALUES ('576','Programming, Consultancy');
INSERT INTO sector(id, value) VALUES ('121','Software, Hardware');
INSERT INTO sector(id, value) VALUES ('122','Telecommunications');
INSERT INTO sector(id, value) VALUES ('22','Tourism');
INSERT INTO sector(id, value) VALUES ('141','Translation services');
INSERT INTO sector(id, value) VALUES ('21','Transport and Logistics');
INSERT INTO sector(id, value) VALUES ('111','Air');
INSERT INTO sector(id, value) VALUES ('114','Rail');
INSERT INTO sector(id, value) VALUES ('112','Road');
INSERT INTO sector(id, value) VALUES ('113','Water');

INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('1','1', '19');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('2','1', '18');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('3','1', '6');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('4','6', '324');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('5','6', '43');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('6','6','42');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('7','6','40');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('8','6','39');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('9','6','437');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('10','6','378');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('11','1','13');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('12','13','389');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('13','13','385');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('14','13','390');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('15','13','98');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('16','13','101');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('17','13','392');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('18','13','394');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('19','13','341');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('20','13','99');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('21','1','12');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('22','12','94');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('23','12','91');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('24','12','224');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('25','12','97');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('26','97','271');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('27','97','269');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('28','97','230');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('29','12','93');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('31','12','508');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('32','12','227');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('33','1','11');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('34','11','67');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('35','11','263');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('36','11','267');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('37','11','542');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('38','542','75');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('39','542','62');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('40','542','69');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('41','542','66');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('42','1','9');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('43','9','54');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('44','9','556');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('45','9','559');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('46','559','55');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('47','559','57');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('48','559','53');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('49','99','560');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('50','1','5');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('51','5','148');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('52','5','150');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('53','5','145');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('54','1','7');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('55','7','44');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('56','7','45');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('57','1','8');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('58','8','337');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('59','8','51');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('60','8','47');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('62','3','37');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('63','3','29');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('64','3','33');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('66','2','25');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('67','2','35');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('68','2','28');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('69','28','581');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('70','28','576');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('71','28','121');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('72','28','122');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('73','2','22');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('74','2','141');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('75','2','21');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('76','21','111');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('77','21','114');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('78','21','112');
INSERT INTO sector_to_sector(id, parent_id, child_id) VALUES ('79','21','113');